### ISSUE TITLE
Getting data from an external server via an API

### ISSUE THREAD

**Issue by JTBellStudent** [stevenaeola/proggold_2324#16]
In a practical a few weeks ago, you provided a link to this page: https://apipheny.io/free-api/. Can you demonstrate how we could integrate one of these into our website and also discuss if that's something we should be doing or only could do? I thought we were supposed to create the server, but is it that we create a server that may request data from other servers? Clarification would be appreciated!

**Comment by stevenaeola** [comment]
This is not required for the second assignment
